### ISSUE TITLE
MS4: Learnings from MS1-4 from All

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/525_group_15#14]
Write down your own learnings from the different parts of the milestones.

**Comment by lennonay** [comment]
Milestone 1:
- Handling of large datasets, exploring ways to reduce loading time including changing data format and only loading the data we need.

Milestone 2:
- Created EC2 instance and hosted jupyterhub
- Setting up S3 bucket

**Comment by kenuiuc** [comment]
### Milestones Reflection

- When data files are too big to fit into RAM, locally we can do some tweaks sush as: Add swap spaces, use column-oriented file format, load in smaller batches and read/write data to disk via deserialization/serialization.

- We can set up collaborative environments in the cloud using AWS EC2, S3 and JupyterHub. Uer authentication and firewall configurations are important to consider when you spin up EC2 instances.

- AWS EMR and Hadoop/spark technologies are useful for processing data sience/data engineering tasks in a distributed manner. `pyspark` provides ainterface to spark that allows us to write data analysis script in a similar way to `scikit-learn`.

- Using `flask` we can provide our ML models as simple web services.

**Comment by pengzh313** [comment]
All reflections have been added to milestone 4 notebook.
