### ISSUE TITLE
Docs: Answers to discussion questions

### ISSUE THREAD

**Issue by tieandrews** [UBC-MDS/525_group_15#2]
Please discuss any challenges or difficulties you faced when dealing with this large amount of data on your laptop. You can stop combining the data if it takes more than 30 minutes. Briefly explain your approach to overcoming the challenges or reasons why you could not overcome them.

**Comment by kenuiuc** [comment]
The combining takes a lot memory. Since my laptop only has 4GB RAM, the notebook kernel crashed when it ran out of RAM. Then I added 8GB swap to the system and this time the combining code ran fine. The processing took 28 minutes and I think it's so slow mainly because it's using a lot swap.

**Comment by tieandrews** [comment]
One big challenge I faced was getting the pyarrow and rpy_arrow to load and run properly, ended up being an order of operations of importing the packages. The resulting order resolved the issue:
```
import rpy2
os.environ['R_HOME'] = "C:\\Users\\tyand\\miniconda3\\envs\\525_2023\\Lib\\R"
# to use R cll magic
%load_ext rpy2.ipython
# keep this below load_ext command, bug makes it break if it is above, SOF issue: https://github.com/rpy2/rpy2/issues/874
import rpy2_arrow.pyarrow_rarrow as pyra
```
If the last import was moved above the %loadext command it received an unhelpful error for which this rpy2 GH issue is standing but not clear on what causes/resolves it: https://github.com/rpy2/rpy2/issues/874 

In the future I'm going to avoid mixing R and Python!
